FROM gcr.io/istio-release/citadel:1.0.2
FROM gcr.io/istio-release/galley:1.0.2
FROM gcr.io/istio-release/proxyv2:1.0.2
FROM gcr.io/istio-release/grafana:1.0.2
FROM gcr.io/istio-release/mixer:1.0.2
FROM gcr.io/istio-release/servicegraph:1.0.2
FROM gcr.io/istio-release/pilot:1.0.2
FROM gcr.io/istio-release/sidecar_injector:1.0.2
FROM gcr.io/istio-release/proxy_init:1.0.2

